In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('precision',3)
#shows only 3 decimals

In [2]:
#2nd data frame

In [3]:
europels=['Albania', 'Andorra', 'Armenia', 'Austria', 'Azerbaijan', 'Belarus', 'Belgium', 'Bosnia-Herzegovina', 'Bulgaria', 'Croatia' ,'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy', 'Kosovo', 'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macedonia', 'Malta', 'Moldova', 'Monaco', 'Montenegro', 'Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'San Marino', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Turkey', 'Ukraine', 'United Kingdom', 'England', 'Northern Ireland', 'Scotland', 'Wales', 'Vatican City']
#list of european countries

In [4]:
suicideDf= pd.read_csv(r'C:\Users\sh9wn\Desktop\suicides.csv')

In [5]:
suicideDf.head()

,country,year,sex,age,suicides_no,population,suicides/100k pop,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,"2,156,624,900",796,Boomers

In [6]:
#merge?

In [7]:
EUdivorce= pd.read_excel(r'C:\Users\sh9wn\Desktop\divorce statistics euro.xlsx', sheet_name='Sheet2')

In [8]:
EUdivorce
#! use jupyter lab

,time,2006,Unnamed: 2,2007,Unnamed: 4,2008,Unnamed: 6,2009,Unnamed: 8,2010,...,2013,Unnamed: 16,2014,Unnamed: 18,2015,Unnamed: 20,2016,Unnamed: 22,2017,Unnamed: 24
0,Country,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,European Union - 28 countries,2.1,NaN,2.1,NaN,2,NaN,1.9,NaN,2,...,1.9,NaN,1.8,NaN,1.9,NaN,:,NaN,:,NaN
2,European Union - 27 countries (2007-2013),2.1,NaN,2.1,NaN,2,NaN,1.9,NaN,2,...,1.9,NaN,:,NaN,:,NaN,:,NaN,:,NaN
3,Euro area (19 countries),:,NaN,:,NaN,:,NaN,:,NaN,:,...,1.8,NaN,:,NaN,:,NaN,:,NaN,:,NaN
4,Euro area (18 countries),2.1,NaN,2,NaN,2,NaN,1.9,NaN,1.9,...,1.8,NaN,:,NaN,:,NaN,:,NaN,:,NaN
5,Belgium,2.8,NaN,2.8,NaN,3.3,NaN,3,NaN,2.7,...,2.2,NaN,2.2,NaN,2.2,NaN,2.1,NaN,2,NaN
6,Bulgaria,2,NaN,2.2,NaN,1.9,NaN,1.6,NaN,1.5,...,1.5,NaN,1.5,NaN,1.5,NaN,1.5,NaN,1.5,NaN
7,Czechia,3.1,NaN,3,NaN,3,NaN,2.8,NaN,2.9,...,2.7,NaN,2.5,NaN,2.5,NaN,2.4,NaN,2.4,NaN
8,Denmark,2.6,NaN,2.6,NaN,2.7,NaN,2.7,NaN,2.6,...,3.4,NaN,3.4,NaN,2.9,NaN,3,NaN,2.6,NaN
9,Germany (until 1990 former territory of the FRG),2.3,NaN,2.3,NaN,2.3,NaN,2.3,NaN,2.3,...,2.1,NaN,2.1,NaN,2,NaN,2,NaN,1.9,NaN
10,Estonia,2.8,NaN,2.8,NaN,2.6,NaN,2.4,NaN,2.2,...,2.5,NaN,2.4,NaN,2.6,NaN,2.5,NaN,2.5,NaN
11,Ireland,0.9,NaN,0.8,NaN,0.8,NaN,0.7,NaN,0.7,...,0.6,NaN,0.6,NaN,0.7,NaN,:,NaN,:,NaN
12,Greece,1.2,NaN,1.2,NaN,1.2,NaN,1.2,NaN,1.2,...,1.5,NaN,1.3,NaN,1.4,NaN,1,NaN,1.8,NaN
13,Spain,2.9,NaN,2.8,NaN,2.4,NaN,2.1,NaN,2.2,...,2,NaN,2.2,NaN,2.1,NaN,2.1,NaN,2.1,NaN
14,France,2.2,NaN,2.1,NaN,2.1,NaN,2,NaN,2.1,...,1.9,NaN,1.9,NaN,1.9,NaN,1.9,NaN,:,NaN
15,France (metropolitan),2.2,NaN,2.1,NaN,2.1,NaN,:,NaN,2.1,...,:,NaN,:,NaN,:,NaN,:,NaN,:,NaN
16,Croatia,1.1,NaN,1.1,NaN,1.2,NaN,1.2,NaN,1.2,...,1.4,NaN,1.4,NaN,1.4,NaN,1.7,NaN,1.5,NaN
17,Italy,0.9,NaN,0.9,NaN,0.9,NaN,0.9,NaN,0.9,...,0.9,NaN,0.9,NaN,1.4,NaN,1.6,NaN,1.5,NaN
18,Cyprus,2.3,NaN,2.1,NaN,2.1,NaN,2.2,NaN,2.3,...,2.2,NaN,2.2,NaN,2.1,NaN,2.3,NaN,2.2,NaN
19,Latvia,3.3,NaN,3.4,NaN,2.9,NaN,2.4,NaN,2.4,...,3.5,NaN,3.1,NaN,2.6,NaN,3.1,NaN,3.1,NaN
20,Lithuania,3.4,NaN,3.5,NaN,3.2,NaN,2.9,NaN,3.2,...,3.4,NaN,3.3,NaN,3.2,NaN,3.1,NaN,3,NaN
21,Luxembourg,2.5,NaN,2.3,NaN,2,NaN,2.1,NaN,2.1,...,2.1,NaN,2.6,NaN,2.4,NaN,2.1,NaN,2,NaN
22,Hungary,2.5,NaN,2.5,NaN,2.5,NaN,2.4,NaN,2.4,...,2,NaN,2,NaN,2.1,NaN,2,NaN,1.9,NaN
23,Malta,:,NaN,:,NaN,:,NaN,:,NaN,:,...,0.8,NaN,0.7,NaN,0.8,NaN,0.8,NaN,0.7,NaN
24,Netherlands,1.9,NaN,2,NaN,2,NaN,1.9,NaN,2,...,2,NaN,2.1,NaN,2,NaN,2,NaN,1.9,NaN
25,Austria,2.5,NaN,2.5,NaN,2.4,NaN,2.3,NaN,2.1,...,1.9,NaN,1.9,NaN,1.9,NaN,1.8,NaN,1.8,NaN
26,Poland,1.9,NaN,1.7,NaN,1.7,NaN,1.7,NaN,1.6,...,1.7,NaN,1.7,NaN,1.8,NaN,1.7,NaN,1.7,NaN
27,Portugal,2.3,NaN,2.4,NaN,2.5,NaN,2.5,NaN,2.6,...,2.2,NaN,2.1,NaN,2.3,NaN,2.2,NaN,2.1,NaN
28,Romania,1.5,NaN,1.7,NaN,1.7,NaN,1.6,NaN,1.6,...,1.4,NaN,1.4,NaN,1.6,NaN,1.5,NaN,1.6,NaN
29,Slovenia,1.2,NaN,1.3,NaN,1.1,NaN,1.1,NaN,1.2,...,1.1,NaN,1.2,NaN,1.2,NaN,1.2,NaN,1.2,NaN
30,Slovakia,2.4,NaN,2.3,NaN,2.4,NaN,2.4,NaN,2.2,...,2,NaN,1.9,NaN,1.8,NaN,1.7,NaN,1.8,NaN
31,Finland,2.5,NaN,2.5,NaN,2.5,NaN,2.5,NaN,2.5,...,2.5,NaN,2.5,NaN,2.5,NaN,2.5,NaN,2.4,NaN
32,Sweden,2.2,NaN,2.3,NaN,2.3,NaN,2.4,NaN,2.5,...,2.8,NaN,2.7,NaN,2.5,NaN,2.4,NaN,2.4,NaN
33,United Kingdom,2.4,NaN,2.3,NaN,2.2,NaN,2,NaN,2.1,...,2,NaN,1.9,NaN,1.7,NaN,1.8,NaN,:,NaN
34,Iceland,1.6,NaN,1.7,NaN,1.7,NaN,1.7,NaN,1.8,...,:,NaN,:,NaN,:,NaN,:,NaN,:,NaN
35,Liechtenstein,2.3,NaN,2.8,NaN,2.8,NaN,2.7,NaN,2.4,...,:,NaN,:,NaN,:,NaN,:,NaN,:,NaN
36,Norway,2.3,NaN,2.2,NaN,2.1,NaN,2.1,NaN,2.1,...,2,NaN,1.9,NaN,1.9,NaN,1.9,NaN,2,NaN
37,Switzerland,2.8,NaN,2.6,NaN,2.6,NaN,2.5,NaN,2.8,...,2.1,NaN,2,NaN,2.1,NaN,2,NaN,1.9,NaN
38,Montenegro,0.8,NaN,0.7,NaN,0.7,NaN,0.7,NaN,0.8,...,0.8,NaN,0.9,NaN,0.9,NaN,1.1,NaN,1.2,NaN
39,North Macedonia,0.7,NaN,0.7,NaN,0.6,NaN,0.6,NaN,0.8,...,1,NaN,1.1,NaN,1,NaN,1,NaN,1,NaN
40,Albania,1.3,NaN,1,NaN,1.1,NaN,:,NaN,:,...,:,NaN,1.5,NaN,1.3,NaN,1.9,NaN,1.6,NaN
41,Serbia,1.1,NaN,1.2,NaN,1.2,NaN,1.2,NaN,0.9,...,1.1,NaN,1.1,NaN,1.3,NaN,1.3,NaN,1.3,NaN
42,Turkey,1.3,NaN,1.3,NaN,1.4,NaN,1.6,NaN,1.6,...,1.6,NaN,1.7,NaN,1.7,NaN,1.6,NaN,1.6,NaN
43,Andorra,:,NaN,:,NaN,:,NaN,:,NaN,:,...,:,NaN,:,NaN,:,NaN,:,NaN,:,NaN
44,Belarus,3.3,NaN,3.7,NaN,3.8,NaN,3.7,NaN,3.9,...,3.8,NaN,3.7,NaN,3.5,NaN,3.4,NaN,3.4,NaN
45,Bosnia and Herzegovina,0.4,NaN,0.5,NaN,0.4,NaN,0.4,NaN,0.4,...,:,NaN,:,NaN,:,NaN,:,NaN,:,NaN
46,Kosovo (under United Nations Security Council ...,0.7,NaN,0.7,NaN,0.5,NaN,0.7,NaN,:,...,:,NaN,:,NaN,0.7,NaN,0.6,NaN,0.6,NaN
47,Moldova,3.5,NaN,3.9,NaN,3.5,NaN,3.3,NaN,3.2,...,:,NaN,:,NaN,:,NaN,:,NaN,:,NaN
48,Monaco,:,NaN,:,NaN,:,NaN,:,NaN,:,...,:,NaN,:,NaN,:,NaN,:,NaN,:,NaN
49,Russia,4.5,NaN,4.8,NaN,5,NaN,4.9,NaN,4.5,...,:,NaN,:,NaN,:,NaN,:,NaN,:,NaN
50,San Marino,2.8,NaN,2.1,NaN,2.2,NaN,:,NaN,:,...,:,NaN,:,NaN,:,NaN,:,NaN,:,NaN
51,Ukraine,3.8,NaN,3.8,NaN,5.3,NaN,3.2,NaN,2.8,...,:,NaN,:,NaN,3,NaN,3.1,NaN,3,NaN
52,Armenia,0.9,NaN,0.9,NaN,0.9,NaN,0.9,NaN,0.9,...,:,NaN,:,NaN,1.2,NaN,1.2,NaN,:,NaN
53,Azerbaijan,0.9,NaN,1,NaN,0.9,NaN,0.9,NaN,1,...,1.2,NaN,1.3,NaN,1.3,NaN,1.3,NaN,1.5,NaN
54,Georgia,0.5,NaN,0.5,NaN,0.7,NaN,0.9,NaN,1.1,...,:,NaN,:,NaN,2.4,NaN,2.6,NaN,2.7,NaN

In [9]:
#drop error columns
EUdivorce.drop(columns=['Unnamed: 2','Unnamed: 4','Unnamed: 6','Unnamed: 8','Unnamed: 10','Unnamed: 12','Unnamed: 14','Unnamed: 16','Unnamed: 18','Unnamed: 20','Unnamed: 22','Unnamed: 24'], inplace=True)

In [10]:
EUdivorce = EUdivorce.iloc[5:]
#drop non useful rows

In [11]:
EUdivorce= EUdivorce.rename(columns={'time':'country_name'})

In [12]:
EUdivorce.set_index('country_name',inplace=True)
#index set to country name for easy navigation

In [13]:
EUdivorce= EUdivorce.apply(lambda x: x.replace(':',np.nan))
#replace : with nan

In [14]:
EUdivorce.dropna(thresh=9,inplace=True)
#drop results with more than 3 nan's

In [15]:
EUdivorce.fillna(axis=1,method='ffill',inplace=True)
#used ffill from last valid year in row

In [16]:
EUdivorce= EUdivorce.astype(float)

In [17]:
EUdivorce.reset_index('country_name',inplace=True)

In [18]:
EUdivorce.country_name = EUdivorce.country_name.apply(lambda x: x.split(' ')[0])
#remove extra wording from Germany and Kosovo

In [19]:
EUdivorce.set_index('country_name',inplace=True)

In [20]:
EUdivorce.rename(index={'United':'United Kingdom', 'North':'Macedonia', 'Czechia': 'Czech Republic'},inplace=True)

In [21]:
EUdivorce['mean']= EUdivorce.iloc[:][EUdivorce.columns].mean(axis=1)
#created avg of all years for each country

In [22]:
EUdivorce

,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,mean
country_name,,,,,,,,,,,,,
Belgium,2.8,2.8,3.3,3.0,2.7,2.5,2.3,2.2,2.2,2.2,2.1,2.0,2.508
Bulgaria,2.0,2.2,1.9,1.6,1.5,1.4,1.6,1.5,1.5,1.5,1.5,1.5,1.642
Czech Republic,3.1,3.0,3.0,2.8,2.9,2.7,2.5,2.7,2.5,2.5,2.4,2.4,2.708
Denmark,2.6,2.6,2.7,2.7,2.6,2.6,2.8,3.4,3.4,2.9,3.0,2.6,2.825
Germany,2.3,2.3,2.3,2.3,2.3,2.3,2.2,2.1,2.1,2.0,2.0,1.9,2.175
Estonia,2.8,2.8,2.6,2.4,2.2,2.3,2.4,2.5,2.4,2.6,2.5,2.5,2.500
Ireland,0.9,0.8,0.8,0.7,0.7,0.6,0.6,0.6,0.6,0.7,0.7,0.7,0.700
Greece,1.2,1.2,1.2,1.2,1.2,1.1,1.3,1.5,1.3,1.4,1.0,1.8,1.283
Spain,2.9,2.8,2.4,2.1,2.2,2.2,2.2,2.0,2.2,2.1,2.1,2.1,2.275
France,2.2,2.1,2.1,2.0,2.1,2.0,2.0,1.9,1.9,1.9,1.9,1.9,2.000
Croatia,1.1,1.1,1.2,1.2,1.2,1.3,1.3,1.4,1.4,1.4,1.7,1.5,1.317
Italy,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,1.4,1.6,1.5,1.050
Cyprus,2.3,2.1,2.1,2.2,2.3,2.3,2.4,2.2,2.2,2.1,2.3,2.2,2.225
Latvia,3.3,3.4,2.9,2.4,2.4,4.0,3.6,3.5,3.1,2.6,3.1,3.1,3.117
Lithuania,3.4,3.5,3.2,2.9,3.2,3.4,3.5,3.4,3.3,3.2,3.1,3.0,3.258
Luxembourg,2.5,2.3,2.0,2.1,2.1,2.3,2.0,2.1,2.6,2.4,2.1,2.0,2.208
Hungary,2.5,2.5,2.5,2.4,2.4,2.3,2.2,2.0,2.0,2.1,2.0,1.9,2.233
Netherlands,1.9,2.0,2.0,1.9,2.0,2.0,2.1,2.0,2.1,2.0,2.0,1.9,1.992
Austria,2.5,2.5,2.4,2.3,2.1,2.1,2.0,1.9,1.9,1.9,1.8,1.8,2.100
Poland,1.9,1.7,1.7,1.7,1.6,1.7,1.7,1.7,1.7,1.8,1.7,1.7,1.717
Portugal,2.3,2.4,2.5,2.5,2.6,2.5,2.4,2.2,2.1,2.3,2.2,2.1,2.342
Romania,1.5,1.7,1.7,1.6,1.6,1.8,1.6,1.4,1.4,1.6,1.5,1.6,1.583
Slovenia,1.2,1.3,1.1,1.1,1.2,1.1,1.2,1.1,1.2,1.2,1.2,1.2,1.175
Slovakia,2.4,2.3,2.4,2.4,2.2,2.1,2.0,2.0,1.9,1.8,1.7,1.8,2.083
Finland,2.5,2.5,2.5,2.5,2.5,2.5,2.4,2.5,2.5,2.5,2.5,2.4,2.483
Sweden,2.2,2.3,2.3,2.4,2.5,2.5,2.5,2.8,2.7,2.5,2.4,2.4,2.458
United Kingdom,2.4,2.3,2.2,2.0,2.1,2.1,2.0,2.0,1.9,1.7,1.8,1.8,2.025
Norway,2.3,2.2,2.1,2.1,2.1,2.1,2.0,2.0,1.9,1.9,1.9,2.0,2.050
Switzerland,2.8,2.6,2.6,2.5,2.8,2.2,2.2,2.1,2.0,2.1,2.0,1.9,2.317
Montenegro,0.8,0.7,0.7,0.7,0.8,0.8,0.8,0.8,0.9,0.9,1.1,1.2,0.850
Macedonia,0.7,0.7,0.6,0.6,0.8,0.9,0.9,1.0,1.1,1.0,1.0,1.0,0.858
Serbia,1.1,1.2,1.2,1.2,0.9,1.1,1.0,1.1,1.1,1.3,1.3,1.3,1.150
Turkey,1.3,1.3,1.4,1.6,1.6,1.6,1.6,1.6,1.7,1.7,1.6,1.6,1.550
Belarus,3.3,3.7,3.8,3.7,3.9,4.1,4.1,3.8,3.7,3.5,3.4,3.4,3.700
Kosovo,0.7,0.7,0.5,0.7,0.7,0.8,0.7,0.7,0.7,0.7,0.6,0.6,0.675
Ukraine,3.8,3.8,5.3,3.2,2.8,1.4,1.1,1.1,1.1,3.0,3.1,3.0,2.725
Azerbaijan,0.9,1.0,0.9,0.9,1.0,1.2,1.2,1.2,1.3,1.3,1.3,1.5,1.142
Georgia,0.5,0.5,0.7,0.9,1.1,1.3,1.3,1.3,1.3,2.4,2.6,2.7,1.383

In [23]:
eurolats= pd.read_excel(r'C:\Users\sh9wn\Desktop\euro lats.xlsx')
eurolats.head()
#adding latitude

   latitude                  name
0    42.546               Andorra
1    23.424  United Arab Emirates
2    33.939           Afghanistan
3    17.061   Antigua and Barbuda
4    18.221              Anguilla

In [24]:
eurolats = eurolats[eurolats['name'].isin(europels)]

In [25]:
eurolats.rename(columns={'name':'country_name'},inplace=True)

In [26]:
eurolats.set_index('country_name',inplace=True)

In [27]:
EUdivorce= pd.merge(EUdivorce,eurolats, how='left',on='country_name')
EUdivorce.head()

,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,mean,latitude
country_name,,,,,,,,,,,,,,
Belgium,2.8,2.8,3.3,3.0,2.7,2.5,2.3,2.2,2.2,2.2,2.1,2.0,2.508,50.504
Bulgaria,2.0,2.2,1.9,1.6,1.5,1.4,1.6,1.5,1.5,1.5,1.5,1.5,1.642,42.734
Czech Republic,3.1,3.0,3.0,2.8,2.9,2.7,2.5,2.7,2.5,2.5,2.4,2.4,2.708,49.817
Denmark,2.6,2.6,2.7,2.7,2.6,2.6,2.8,3.4,3.4,2.9,3.0,2.6,2.825,56.264
Germany,2.3,2.3,2.3,2.3,2.3,2.3,2.2,2.1,2.1,2.0,2.0,1.9,2.175,51.166